// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgR8eenoLsdWc9J5U6ySSwTl61UdQoVCg',
    appId: '1:446913494218:web:da5cd1aa429d187aa10833',
    messagingSenderId: '446913494218',
    projectId: 'flutter-firebase-4a047',
    authDomain: 'flutter-firebase-4a047.firebaseapp.com',
    storageBucket: 'flutter-firebase-4a047.firebasestorage.app',
    measurementId: 'G-DG00YYKMVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ__23ymI0XrpYN7ST5qchlJo-OoZTl_8',
    appId: '1:446913494218:android:b33b30b3d3a8c7e2a10833',
    messagingSenderId: '446913494218',
    projectId: 'flutter-firebase-4a047',
    storageBucket: 'flutter-firebase-4a047.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVMIhRq0_sdPYDMWPXJ4uO8wJFmEXeXiQ',
    appId: '1:446913494218:ios:2374013f73e7234fa10833',
    messagingSenderId: '446913494218',
    projectId: 'flutter-firebase-4a047',
    storageBucket: 'flutter-firebase-4a047.firebasestorage.app',
    iosBundleId: 'com.example.tokoBuah',
  );
}
